-- MySQL Script generated by MySQL Workbench
-- lun 31 ene 2022 18:00:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kraid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kraid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kraid` ;
USE `kraid` ;

-- -----------------------------------------------------
-- Table `kraid`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kraid`.`persona` (
  `_idPersona` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fotoUrl` VARCHAR(100) NULL,
  `telefonoPersona` VARCHAR(45) NULL,
  PRIMARY KEY (`_idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kraid`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kraid`.`alumnos` (
  `matriculaA` VARCHAR(25) NOT NULL,
  `division` VARCHAR(45) NOT NULL,
  `programaEducativo` VARCHAR(45) NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `status` TINYINT NOT NULL,INSERT INTO Sintomas (id_Sintoma, nombreSintomas) VALUES ('1', '["Fiebre", "Escalofríos", "Tos", "Dificultad respiratoria"]');
[5:14 PM]
INSERT INTO statusCovid (_statusCovid, temperatura, fecha, hora, persona__idPersona, Sintomas_id_Sintoma) VALUES ('1', '39.9', '2022-01-27', '18:13:51', '1', '1');
[5:15 PM]
INSERT INTO torre (_idTorre, nombreTorre) VALUES ('1', 'Torre 1'), ('2', 'Torre 2'), ('3', 'Torre 3');
[5:18 PM]
INSERT INTO ingreso (_idIngreso, fechaIngreso, fechaSalida, persona__idPersona, fkEntrada, fkSalida) VALUES ('10', '2022-02-24 16:18:15', NULL, '1', '1', NULL);
[5:20 PM]
SELECT * FROM alumnos INNER JOIN persona on (alumnos.fk_persona = persona._idPersona);
[5:23 PM]
SELECT * FROM alumnos INNER JOIN persona on (alumnos.fk_persona = persona._idPersona) INNER JOIN statusCovid on (persona._idPersona = statusCovid.persona__idPersona) INNER JOIN Sintomas on (Sintomas.id_Sintoma = statusCovid.Sintomas_id_Sintoma);
  `fk_persona` INT NOT NULL,
  PRIMARY KEY (`matriculaA`),
  INDEX `fk_alumnos_persona_idx` (`fk_persona` ASC) VISIBLE,
  CONSTRAINT `fk_alumnos_persona`
    FOREIGN KEY (`fk_persona`)
    REFERENCES `kraid`.`persona` (`_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
INSERT INTO Sintomas (id_Sintoma, nombreSintomas) VALUES ('1', '["Fiebre", "Escalofríos", "Tos", "Dificultad respiratoria"]');
[5:14 PM]
INSERT INTO statusCovid (_statusCovid, temperatura, fecha, hora, persona__idPersona, Sintomas_id_Sintoma) VALUES ('1', '39.9', '2022-01-27', '18:13:51', '1', '1');
[5:15 PM]
INSERT INTO torre (_idTorre, nombreTorre) VALUES ('1', 'Torre 1'), ('2', 'Torre 2'), ('3', 'Torre 3');
[5:18 PM]
INSERT INTO ingreso (_idIngreso, fechaIngreso, fechaSalida, persona__idPersona, fkEntrada, fkSalida) VALUES ('10', '2022-02-24 16:18:15', NULL, '1', '1', NULL);
[5:20 PM]
SELECT * FROM alumnos INNER JOIN persona on (alumnos.fk_persona = persona._idPersona);
[5:23 PM]
SELECT * FROM alumnos INNER JOIN persona on (alumnos.fk_persona = persona._idPersona) INNER JOIN statusCovid on (persona._idPersona = statusCovid.persona__idPersona) INNER JOIN Sintomas on (Sintomas.id_Sintoma = statusCovid.Sintomas_id_Sintoma);
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kraid`.`torre` (
  `_idTorre` INT NOT NULL,
  `nombreTorre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_idTorre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kraid`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kraid`.`ingreso` (
  `_idIngreso` INT NOT NULL,INSERT INTO Sintomas (id_Sintoma, nombreSintomas) VALUES ('1', '["Fiebre", "Escalofríos", "Tos", "Dificultad respiratoria"]');
[5:14 PM]
INSERT INTO statusCovid (_statusCovid, temperatura, fecha, hora, persona__idPersona, Sintomas_id_Sintoma) VALUES ('1', '39.9', '2022-01-27', '18:13:51', '1', '1');
[5:15 PM]
INSERT INTO torre (_idTorre, nombreTorre) VALUES ('1', 'Torre 1'), ('2', 'Torre 2'), ('3', 'Torre 3');
[5:18 PM]
INSERT INTO ingreso (_idIngreso, fechaIngreso, fechaSalida, persona__idPersona, fkEntrada, fkSalida) VALUES ('10', '2022-02-24 16:18:15', NULL, '1', '1', NULL);
[5:20 PM]
SELECT * FROM alumnos INNER JOIN persona on (alumnos.fk_persona = persona._idPersona);
[5:23 PM]
SELECT * FROM alumnos INNER JOIN persona on (alumnos.fk_persona = persona._idPersona) INNER JOIN statusCovid on (persona._idPersona = statusCovid.persona__idPersona) INNER JOIN Sintomas on (Sintomas.id_Sintoma = statusCovid.Sintomas_id_Sintoma);
  `persona__idPersona` INT NOT NULL,
  `fkEntrada` INT NOT NULL,
  `fkSalida` INT NOT NULL,
  PRIMARY KEY (`_idIngreso`),
  INDEX `fk_ingreso_persona1_idx` (`persona__idPersona` ASC) VISIBLE,
  INDEX `fk_ingreso_torre1_idx` (`fkEntrada` ASC) VISIBLE,
  INDEX `fk_ingreso_torre2_idx` (`fkSalida` ASC) VISIBLE,
  CONSTRAINT `fk_ingreso_persona1`
    FOREIGN KEY (`persona__idPersona`)
    REFERENCES `kraid`.`persona` (`_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_torre1`
    FOREIGN KEY (`fkEntrada`)
    REFERENCES `kraid`.`torre` (`_idTorre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_torre2`
    FOREIGN KEY (`fkSalida`)
    REFERENCES `kraid`.`torre` (`_idTorre`)
    ON DELETE NO ACTIONINSERT INTO Sintomas (id_Sintoma, nombreSintomas) VALUES ('1', '["Fiebre", "Escalofríos", "Tos", "Dificultad respiratoria"]');
[5:14 PM]
INSERT INTO statusCovid (_statusCovid, temperatura, fecha, hora, persona__idPersona, Sintomas_id_Sintoma) VALUES ('1', '39.9', '2022-01-27', '18:13:51', '1', '1');
[5:15 PM]
INSERT INTO torre (_idTorre, nombreTorre) VALUES ('1', 'Torre 1'), ('2', 'Torre 2'), ('3', 'Torre 3');
[5:18 PM]
INSERT INTO ingreso (_idIngreso, fechaIngreso, fechaSalida, persona__idPersona, fkEntrada, fkSalida) VALUES ('10', '2022-02-24 16:18:15', NULL, '1', '1', NULL);
[5:20 PM]
SELECT * FROM alumnos INNER JOIN persona on (alumnos.fk_persona = persona._idPersona);
[5:23 PM]
SELECT * FROM alumnos INNER JOIN persona on (alumnos.fk_persona = persona._idPersona) INNER JOIN statusCovid on (persona._idPersona = statusCovid.persona__idPersona) INNER JOIN Sintomas on (Sintomas.id_Sintoma = statusCovid.Sintomas_id_Sintoma);----------
-- Table `kraid`.`Sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kraid`.`Sintomas` (
  `id_Sintoma` INT NOT NULL,
  `nombreSintomas` JSON NULL,
  PRIMARY KEY (`id_Sintoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kraid`.`statusCovid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kraid`.`statusCovid` (
  `_statusCovid` INT NOT NULL,
  `temperatura` DECIMAL(5,1) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `persona__idPersona` INT NOT NULL,
  `Sintomas_id_Sintoma` INT NOT NULL,
  PRIMARY KEY (`_statusCovid`),
  INDEX `fk_statusCovid_persona1_idx` (`persona__idPersona` ASC) VISIBLE,
  INDEX `fk_statusCovid_Sintomas1_idx` (`Sintomas_id_Sintoma` ASC) VISIBLE,
  CONSTRAINT `fk_statusCovid_persona1`
    FOREIGN KEY (`persona__idPersona`)
    REFERENCES `kraid`.`persona` (`_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statusCovid_Sintomas1`
    FOREIGN KEY (`Sintomas_id_Sintoma`)
    REFERENCES `kraid`.`Sintomas` (`id_Sintoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kraid`.`docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kraid`.`docentes` (
  `matriculaD` VARCHAR(25) NOT NULL,
  `fk_persona` INT NOT NULL,
  `status` TINYINT NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  PRIMARY KEY (`matriculaD`),
  INDEX `fk_docentes_persona1_idx` (`fk_persona` ASC) VISIBLE)
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO persona (_idPersona, nombre, sexo, edad, email, fotoUrl, telefonoPersona) VALUES ('1', 'Julio Andrei Claudio Domínguez', 'Hombre', '22', 'utp0006096@alumno.utpuebla.edu.mx', 'https://sicea.utpuebla.edu.mx/control/fotos/aspirantes/6096.jpg', '2225669899'), ('2', 'Jesús Antonio Mena de la rosa', 'Hombre', '21', 'utp0140516.alumno.utpuebla.edu.mx', 'https://sicea.utpuebla.edu.mx/control/fotos/aspirantes/140516.jpg', '2213425513');
INSERT INTO docentes (matriculaD, fk_persona, status, fechaIngreso) VALUES ('UTP1012', '2', '1', '2012-01-27'); 
INSERT INTO Sintomas (id_Sintoma, nombreSintomas) VALUES ('1', '["Fiebre", "Escalofríos", "Tos", "Dificultad respiratoria"]');
[5:14 PM]
INSERT INTO statusCovid (_statusCovid, temperatura, fecha, hora, persona__idPersona, Sintomas_id_Sintoma) VALUES ('1', '39.9', '2022-01-27', '18:13:51', '1', '1');
[5:15 PM]
INSERT INTO torre (_idTorre, nombreTorre) VALUES ('1', 'Torre 1'), ('2', 'Torre 2'), ('3', 'Torre 3');
[5:18 PM]
INSERT INTO ingreso (_idIngreso, fechaIngreso, fechaSalida, persona__idPersona, fkEntrada, fkSalida) VALUES ('10', '2022-02-24 16:18:15', NULL, '1', '1', NULL);
[5:20 PM]
SELECT * FROM alumnos INNER JOIN persona on (alumnos.fk_persona = persona._idPersona);
[5:23 PM]
SELECT * FROM alumnos INNER JOIN persona on (alumnos.fk_persona = persona._idPersona) INNER JOIN statusCovid on (persona._idPersona = statusCovid.persona__idPersona) INNER JOIN Sintomas on (Sintomas.id_Sintoma = statusCovid.Sintomas_id_Sintoma);