-- MySQL Script generated by MySQL Workbench
-- Tue Feb  1 22:52:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemacontrolcovid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemacontrolcovid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemacontrolcovid` ;
USE `sistemacontrolcovid` ;

-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`tiposPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacontrolcovid`.`tiposPersona` (
  `_idTipos` INT NOT NULL AUTO_INCREMENT,
  `tipoPersona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_idTipos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacontrolcovid`.`persona` (
  `matricula` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(45) NOT NULL,
  `apellidoM` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fotoUrl` VARCHAR(100) NOT NULL,
  `telefonoPersona` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(75) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `fechaIngreso` DATE NOT NULL,
  `fkTipoPersona` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_persona_tiposPersona1_idx` (`fkTipoPersona` ASC) ,
  CONSTRAINT `fk_persona_tiposPersona1`
    FOREIGN KEY (`fkTipoPersona`)
    REFERENCES `sistemacontrolcovid`.`tiposPersona` (`_idTipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`torre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacontrolcovid`.`torre` (
  `_idTorre` INT NOT NULL AUTO_INCREMENT,
  `nombreTorre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_idTorre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacontrolcovid`.`ingreso` (
  `_idIngreso` INT NOT NULL AUTO_INCREMENT,
  `fechaIngreso` DATETIME NOT NULL,
  `fechaSalida` DATETIME NULL,
  `fkpersona` VARCHAR(45) NOT NULL,
  `fkEntrada` INT NOT NULL,
  `fkSalida` INT NULL,
  PRIMARY KEY (`_idIngreso`),
  INDEX `fk_ingreso_persona1_idx` (`fkpersona` ASC) ,
  INDEX `fk_ingreso_torre1_idx` (`fkEntrada` ASC) ,
  INDEX `fk_ingreso_torre2_idx` (`fkSalida` ASC) ,
  CONSTRAINT `fk_ingreso_persona1`
    FOREIGN KEY (`fkpersona`)
    REFERENCES `sistemacontrolcovid`.`persona` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_torre1`
    FOREIGN KEY (`fkEntrada`)
    REFERENCES `sistemacontrolcovid`.`torre` (`_idTorre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_torre2`
    FOREIGN KEY (`fkSalida`)
    REFERENCES `sistemacontrolcovid`.`torre` (`_idTorre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`Sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacontrolcovid`.`Sintomas` (
  `id_Sintoma` INT NOT NULL AUTO_INCREMENT,
  `nombreSintomas` JSON NOT NULL,
  PRIMARY KEY (`id_Sintoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`statusCovid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacontrolcovid`.`statusCovid` (
  `_statusCovid` INT NOT NULL AUTO_INCREMENT,
  `temperatura` DECIMAL(5,1) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `fkpersona` VARCHAR(45) NOT NULL ,
  `fksintomas` INT NOT NULL UNIQUE,
  PRIMARY KEY (`_statusCovid`),
  INDEX `fk_statusCovid_persona1_idx` (`fkpersona` ASC) ,
  INDEX `fk_statusCovid_Sintomas1_idx` (`fksintomas` ASC) ,
  CONSTRAINT `fk_statusCovid_persona1`
    FOREIGN KEY (`fkpersona`)
    REFERENCES `sistemacontrolcovid`.`persona` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statusCovid_Sintomas1`
    FOREIGN KEY (`fksintomas`)
    REFERENCES `sistemacontrolcovid`.`Sintomas` (`id_Sintoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- insertar datos de prueba
-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`tipospersona`
-- -----------------------------------------------------
INSERT INTO `tipospersona` (`_idTipos`, `tipoPersona`) 
VALUES (NULL, 'Alumno'),(NULL, 'Docente'), (NULL, 'visitante');
-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`persona`
-- -----------------------------------------------------
INSERT INTO `persona` (`matricula`, `nombre`, `apellidoP`, `apellidoM`, `sexo`, `edad`, `email`, `fotoUrl`, `telefonoPersona`, `contrasena`, `status`, `fechaIngreso`, `fkTipoPersona`) 
VALUES ('UTP0140516', 'Jesús Antonio', 'Mena', 'De la rosa', 'Hombre', '21', 'utp0140516@alumno.utpuebla.edu.mx', 'https://sicea.utpuebla.edu.mx/control/fotos/aspirantes/140516.jpg', 
'2213425514', '2d07d76e8d3767333d91aa48468876be948fafb7d818eb6c3e9248d4181552ea', '1', '2019-11-14', '2'),
('UTP0006096', 'Julio Andrei', 'Claudio', 'Domínguez', 'Hombre', '22', 'utp0006096@alumno.utpuebla.edu.mx', 'https://sicea.utpuebla.edu.mx/control/fotos/aspirantes/6096.jpg', 
'2225669899', '5de6d27f6647d58bb624bd79ea4ed614099d028d4c84aec5b39d1b5b16ef719f', '1', '2019-11-14', '1');
-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`sintomas`
-- -----------------------------------------------------
INSERT INTO `sintomas` (`id_Sintoma`, `nombreSintomas`) 
VALUES (NULL, '[\"Contacto con una persona contagiada por COVID\", \"Ojos irritados\", \"Escalofríos\"]'),
(NULL, '[\"Ninguna de las anteriores\"]');

-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`statuscovid`
-- -----------------------------------------------------
INSERT INTO `statuscovid` (`_statusCovid`, `temperatura`, `fecha`, `hora`, `fkpersona`, `fksintomas`) 
VALUES (NULL, '46.5', '2022-01-29', '07:13:00', 'UTP0140516', '1'),
(NULL, '48.5', '2022-01-29', '15:12:28', 'UTP0006096', '2');
-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`torre`
-- -----------------------------------------------------
INSERT INTO `torre` (`_idTorre`, `nombreTorre`) VALUES (NULL, 'Principal'), (NULL, 'Segunda'), (NULL, 'Tercera');

-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`ingreso`
-- -----------------------------------------------------
INSERT INTO `ingreso` (`_idIngreso`, `fechaIngreso`, `fechaSalida`, `fkpersona`, `fkEntrada`, `fkSalida`) 
VALUES (NULL, '2022-02-02 23:38:23', NULL, 'UTP0140516', '1', NULL), (NULL, '2022-02-02 06:38:23.000000', NULL, 'UTP0006096', '2', NULL);

-- -----------------------------------------------------
-- Table `sistemacontrolcovid`.`ingreso`-update
-- -----------------------------------------------------
UPDATE `ingreso` SET `fechaSalida` = '2022-02-01 17:42:13', `fkSalida` = '2' WHERE `ingreso`.`_idIngreso` = 1;
