-- MySQL Script generated by MySQL Workbench
-- Wed Feb  9 23:08:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema by1k0q2edmxuyzinpwft
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema by1k0q2edmxuyzinpwft
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `by1k0q2edmxuyzinpwft` ;
-- USE `by1k0q2edmxuyzinpwft` ;

-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by1k0q2edmxuyzinpwft`.`personas` (
  `_idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(45) NOT NULL,
  `apellidoM` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`_idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`accesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by1k0q2edmxuyzinpwft`.`accesos` (
  `_idAcceso` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `entradas` JSON NOT NULL,
  `salidas` JSON NULL,
  `fkPersona` INT NOT NULL,
  PRIMARY KEY (`_idAcceso`),
  INDEX `fk_acceso_persona1_idx` (`fkPersona` ASC) ,
  CONSTRAINT `fk_acceso_persona1`
    FOREIGN KEY (`fkPersona`)
    REFERENCES `by1k0q2edmxuyzinpwft`.`personas` (`_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by1k0q2edmxuyzinpwft`.`sintomas` (
  `_idSintoma` INT NOT NULL AUTO_INCREMENT,
  `nombreSintomas` JSON NOT NULL,
  PRIMARY KEY (`_idSintoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`statusCovid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by1k0q2edmxuyzinpwft`.`statusCovid` (
  `_idStatusCovid` INT NOT NULL AUTO_INCREMENT,
  `temperatura` DECIMAL(5,1) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `fkSintomas` INT NOT NULL,
  `fkPersona` INT NOT NULL,
  PRIMARY KEY (`_idStatusCovid`),
  INDEX `fk_statusCovid_sintomas1_idx` (`fkSintomas` ASC) ,
  INDEX `fk_statusCovid_persona1_idx` (`fkPersona` ASC) ,
  CONSTRAINT `fk_statusCovid_sintomas1`
    FOREIGN KEY (`fkSintomas`)
    REFERENCES `by1k0q2edmxuyzinpwft`.`sintomas` (`_idSintoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statusCovid_persona1`
    FOREIGN KEY (`fkPersona`)
    REFERENCES `by1k0q2edmxuyzinpwft`.`personas` (`_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`tipoEmpleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by1k0q2edmxuyzinpwft`.`tipoEmpleado` (
  `_idTipos` INT NOT NULL AUTO_INCREMENT,
  `tipoEmpleado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_idTipos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`visitantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by1k0q2edmxuyzinpwft`.`visitantes` (
  `_idVisitante` INT NOT NULL AUTO_INCREMENT,
  `destino` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(45) NULL,
  `fkPersona` INT NOT NULL,
  PRIMARY KEY (`_idVisitante`),
  INDEX `fk_visitantes_persona1_idx` (`fkPersona` ASC) ,
  CONSTRAINT `fk_visitantes_persona1`
    FOREIGN KEY (`fkPersona`)
    REFERENCES `by1k0q2edmxuyzinpwft`.`personas` (`_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by1k0q2edmxuyzinpwft`.`estudiantes` (
  `matricula` VARCHAR(20) NOT NULL,
  `fotoUrl` TEXT NOT NULL,
  `academia` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  `cuatrimestre` INT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `email` VARCHAR(55) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `fkPersona` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_estudiantes_persona1_idx` (`fkPersona` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  CONSTRAINT `fk_estudiantes_persona1`
    FOREIGN KEY (`fkPersona`)
    REFERENCES `by1k0q2edmxuyzinpwft`.`personas` (`_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by1k0q2edmxuyzinpwft`.`empleados` (
  `matricula` VARCHAR(45) NOT NULL,
  `fotoUrl` TEXT NOT NULL,
  `email` VARCHAR(55) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `fkPersona` INT NOT NULL,
  `fkTipoEmpleado` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_empleados_tipoEmpleado1_idx` (`fkTipoEmpleado` ASC) ,
  INDEX `fk_empleados_persona1_idx` (`fkPersona` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  CONSTRAINT `fk_empleados_tipoEmpleado1`
    FOREIGN KEY (`fkTipoEmpleado`)
    REFERENCES `by1k0q2edmxuyzinpwft`.`tipoEmpleado` (`_idTipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleados_persona1`
    FOREIGN KEY (`fkPersona`)
    REFERENCES `by1k0q2edmxuyzinpwft`.`personas` (`_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

----------------------------------------------------
-- ----------Insertar datos iniciales ------------------
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`tipoEmpleado`
-- -----------------------------------------------------
INSERT INTO `tipoEmpleado` (`_idTipos`, `tipoEmpleado`) VALUES (NULL, 'Administrador'), (NULL, 'Docente');

-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`personas`
-- -----------------------------------------------------
INSERT INTO `personas` (`_idPersona`, `nombre`, `apellidoP`, `apellidoM`, `sexo`, `fechaNacimiento`) 
VALUES (NULL, 'Jesus Antonio', 'Mena', 'De la rosa', 'Hombre', '2000-10-01'), 
  (NULL, 'Arturo', 'Romero', 'Avendaño', 'Hombre', '2000-02-08'), 
  (NULL, 'Fabiano', 'Rivera', 'Rosas', 'Hombre', '2001-02-08'), 
  (NULL, 'María', 'Amaya ', 'Padrón', 'Mujer', '1999-07-07'), 
  (NULL, 'Guadalupe', 'Lopez', 'Jose', 'Mujer', '1998-12-20'), 
  (NULL, 'Lucero', 'Cruz', 'Garcia', 'Mujer', '2002-10-05'), 
  (NULL, 'Bibiana', 'valdés', 'viviros', 'Mujer', '2002-12-25'), 
  (NULL, 'Mario', 'Guzmán', 'Sánches', 'Hombre', '1999-02-21'), 
  (NULL, 'Carlos', 'Herrera', 'villa', 'Hombre', '2000-03-04'), 
  (NULL, 'Abraham', 'Padilla', 'Vargas', 'Hombre', '2001-05-20');

-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`estudiantes`
-- -----------------------------------------------------
INSERT INTO `estudiantes` (`matricula`, `fotoUrl`, `academia`, `area`, `cuatrimestre`, `status`, `email`, `contrasena`, `fkPersona`) 
VALUES ('UTP0140516', 'https://firebasestorage.googleapis.com/v0/b/sistema-control-covid.appspot.com/o/fotos%2FAlumnos%2F140516.jpg?alt=media&token=567ae47b-5692-4a9a-a8e9-663caf2888ff', 'Tecnologías de la información', 'Desarrollo de Software Multiplataforma', '8', '1', 'utp0140516@alumno.utpuebla.edu.mx', 'eb56f6a061ff2fb9041c99e02390969c9212a3b329f975a53f5d9cf58c238b93', '1'), 
('UTP001350', 'https://firebasestorage.googleapis.com/v0/b/sistema-control-covid.appspot.com/o/fotos%2FAlumnos%2F1350.webp?alt=media&token=07657be7-1aa1-4e3e-801a-1735f013cb4a', 'Negocios', 'Capital Humano', '3', '1', 'utp01350@alumno.utpuebla.edu.mx', '81a18f70d07e5fbf38e4aef1b4982806f2b8b32eb06b623b89aea3dfe060a616', '7'), 
('UTP0257637', 'https://firebasestorage.googleapis.com/v0/b/sistema-control-covid.appspot.com/o/fotos%2FAlumnos%2F257637.jfif?alt=media&token=3241ca7e-2717-4c1f-8107-6a58afe2406b', 'Mecatrónica', 'Sistema de Manufactura', '6', '1', 'utp0257637@alumno.utpuebla.edu.mx', '6b500f0e9bc28ea48b8f85c115f84d233c329f46d46b84b9dcf32fc4ea01d981', '8'),
('UTP024024', 'https://firebasestorage.googleapis.com/v0/b/sistema-control-covid.appspot.com/o/fotos%2FAlumnos%2F24024.jfif?alt=media&token=e3945321-dce6-4b33-94fa-14a602858e0a', 'Tecnologías de la información', 'Desarrollo de Software Multiplataforma', '3', '1', 'utp0024024@alumno.utpuebla.edu.mx', 'ac9c2c34c9f7ad52528c3422af40a66e2e24aaf2a727831255413c9470158984', '9'), 
('UTP025354', 'https://firebasestorage.googleapis.com/v0/b/sistema-control-covid.appspot.com/o/fotos%2FAlumnos%2F25354.jfif?alt=media&token=4302ba2e-9309-45c9-8cfa-15fb265de64b', 'Negocios', 'Capital Humano', '6', '1', 'utp025354@alumno.utpuebla.edu.mx', '55f129ee073e770516f3301d2e413b97fcb49c5f40bc21faeed58a5febfb662c', '10');

-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`empleados`
-- -----------------------------------------------------
INSERT INTO `empleados` (`matricula`, `fotoUrl`, `email`, `contrasena`, `fkPersona`, `fkTipoEmpleado`) 
VALUES ('UTP1', 'https://firebasestorage.googleapis.com/v0/b/sistema-control-covid.appspot.com/o/fotos%2FEmpleados%2F1.webp?alt=media&token=0d6ea3f7-145b-4e5c-9233-297cd4c10c0e','arturo.romero@utpuebla.edu.mx', '8a67b9a136520edf23e38d1883352892d7fb9fc78d18e46e5c57c51d62086a08', '2', '2'), 
('UTP30', 'https://firebasestorage.googleapis.com/v0/b/sistema-control-covid.appspot.com/o/fotos%2FEmpleados%2F30.jpg?alt=media&token=1520b29b-d39b-4075-85b4-6730a2c376ae', 'fabiano.rivera@utpuebla.edu.mx', 'ced34a01165563b096d2644ebaeddecafe0e1d49f3b71ce49e4cc608d1723a0c', '3', '1');

-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`visitantes`
-- -----------------------------------------------------
INSERT INTO `visitantes` (`_idVisitante`, `destino`, `observaciones`, `fkPersona`) 
VALUES (NULL, 'SICE', 'Información de inscripciones ', '4'), 
  (NULL, 'Biblioteca', NULL, '5'), 
  (NULL, 'SICE', NULL, '6');

-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`accesos`
-- -----------------------------------------------------
INSERT INTO `accesos` (`_idAcceso`, `fecha`, `entradas`, `salidas`, `fkPersona`) 
VALUES (NULL, '2022-02-10', '[\r\n    {\r\n        \"hora\": \"07:53:05\",\r\n        \"entrada\": \"Principal\"\r\n    },\r\n    {\r\n        \"hora\": \"10:20:03\",\r\n        \"entrada\": \"Principal\"\r\n    },\r\n    {\r\n        \"hora\": \"10:20:03\",\r\n        \"entrada\": \"Tercera\"\r\n    }\r\n]', '[\r\n    {\r\n        \"hora\": \"10:00\",\r\n        \"salida\": \"Principal\"\r\n    },\r\n    {\r\n        \"hora\": \"10:05\",\r\n        \"salida\": \"Segunda\"\r\n    },\r\n    {\r\n        \"hora\": \"12:59\",\r\n        \"salida\": \"Tercera\"\r\n    }\r\n]', '1'), 
  (NULL, '2022-02-10', '[\r\n    {\r\n        \"hora\": \"07:53:05\",\r\n        \"entrada\": \"Principal\"\r\n    }\r\n]\r\n', '[\r\n    {\r\n        \"hora\": \"09:15:05\",\r\n        \"salida\": \"Principal\"\r\n    }\r\n]\r\n', '2'), 
  (NULL, '2022-02-10', '[\r\n    {\r\n        \"hora\": \"09:20:03\",\r\n        \"entrada\": \"Principal\"\r\n    }\r\n]\r\n', '[\r\n    {\r\n        \"hora\": \"09:20:03\",\r\n        \"salida\": \"Principal\"\r\n    }\r\n]\r\n', '5'), 
  (NULL, '2022-02-10', '[\r\n    {\r\n        \"hora\": \"07:05:03\",\r\n        \"entrada\": \"Principal\"\r\n    }\r\n]\r\n\r\n', NULL, '9');
-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`sintomas`
-- -----------------------------------------------------

INSERT INTO `sintomas` (`_idSintoma`, `nombreSintomas`) 
VALUES (NULL, '[\"Pérdida del olfato\", \"Pérdida del gusto\", \"Contacto con una persona contagiada por COVID\", \"Dolor de articulaciones\"]'), 
  (NULL, '[\"Ninguna de las anteriores\"]'), 
  (NULL, '[\"Fiebre\", \"Tos\"]');
-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`statuscovid`
-- -----------------------------------------------------
INSERT INTO `statusCovid` (`_idStatusCovid`, `temperatura`, `fecha`, `hora`, `fkSintomas`, `fkPersona`) 
VALUES (NULL, '46.5', '2022-02-10', '07:13:00', '3', '1'), 
  (NULL, '47.5', '2022-02-10', '09:15:05', '1', '9'), 
  (NULL, '46.2', '2022-02-11', '09:15:05', '2', '10');


-- -----------------------------------------------------
-- -----------------------------------------------------
---- ---------------------------------------------------




----------------------------------------------------
-- ----------Update de datos-----------------------
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Table `by1k0q2edmxuyzinpwft`.`accesos`
-- -----------------------------------------------------

-- UPDATE `accesos` SET `salidas` = NULL 
--   WHERE `accesos`.`_idAcceso` = 15;








----------------------------------------------------
-- ----------Consultas Inner Joins-----------------------
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `sintomas`, `statuscovid`, personas
-- -----------------------------------------------------

-- SELECT * FROM statuscovid AS s INNER JOIN sintomas AS si ON(s.fkSintomas = si._idSintoma) INNER JOIN personas AS p ON(p._idPersona = s.fkPersona);


-- -----------------------------------------------------
-- Table `accesos`, `perosonas`
-- -----------------------------------------------------

-- SELECT * FROM accesos AS a INNER JOIN personas AS p ON(a.fkPersona = p._idPersona) where _idAcceso = 2;
